namespace: dev

nameOverride: ""

ingress:
  enabled: true
  className: ""
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /,
    cert-manager.io/issuer: "letsencrypt-prod",
    kubernetes.io/ingress.class: "nginx"
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: whoami-dev.ralex.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: whoami-dev-tls
     hosts:
       - whoami-dev.ralex.dev
