namespace: staging

nameOverride: ""

ingress:
  enabled: true
  className: ""
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /,
    cert-manager.io/issuer: "letsencrypt-prod",
    kubernetes.io/ingress.class: "nginx"
  }
  hosts:
    - host: whoami-staging.ralex.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: whoami-staging-tls
     hosts:
       - whoami-staging.ralex.dev
